---
apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app
    author: intelliqit
spec:
  containers:
    - name: voting-app-pod
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80
...